#!/bin/bash
# 
# To the extent possible under law, the person who associated CC0 with
# this code has waived all copyright and related or neighboring rights
# to this code.
# 
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
#

outfn=100_years_stifled.zip
rm -f $outfn

zip $outfn 500.js FileSaver.js fxhash.min.js script.js svg.js two.js index.html LICENSE README.md



