#!/bin/bash
# 
# To the extent possible under law, the person who associated CC0 with
# this code has waived all copyright and related or neighboring rights
# to this code.
# 
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
#

outfn=wip_stair.zip
rm -f $outfn

zip $outfn CCapture.js download.js webm-writer-0.2.0.js script.js index.html style.css m4.js three.js quadtree.js LICENSE LICENSE-three-js README.md

